apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: infra.oktaco.shop
spec:
  group: oktaco.shop
  names:
    kind: Infra
    plural: infra
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              location:
                type: string
                oneOf:
                  - pattern: '^EU$'
                  - pattern: '^US$'
              name:
                type: string
            required:
              - location
              - name
    served: true
    referenceable: true
  claimNames:
    kind: InfraClaim
    plural: infraclaim